In [1]:
import numpy as np
import pandas as pd

In [20]:
year = "2021"
df = pd.read_csv(f"../Data/Procesed data/Cleaned data/{year}_LoL_esports_match_data_from_OraclesElixir.csv",low_memory=False)

In [21]:
df.head()

,gameid,side,p1_name,p1_champion,p1_kills,p1_deaths,p1_pentakill,p1_dpm,p2_name,p2_champion,...,p5_kills,p5_deaths,p5_pentakill,p5_dpm,team,dragons,barons,heralds,towers,result
0,6909-9183,Blue,369,Karma,0,0,0.0,539.8244,Karsa,Pantheon,...,0,4,0.0,71.4439,Top Esports,2.0,0.0,NaN,3.0,0
1,6909-9183,Red,Bin,Aatrox,1,0,0.0,230.0780,SofM,Nidalee,...,0,2,0.0,113.1220,Suning,2.0,1.0,NaN,6.0,1
2,6909-9184,Blue,369,Jax,0,7,0.0,346.8273,Karsa,Hecarim,...,1,6,0.0,166.6399,Top Esports,3.0,2.0,NaN,6.0,0
3,6909-9184,Red,Bin,Camille,11,3,0.0,688.4070,SofM,Lillia,...,0,4,0.0,316.5462,Suning,2.0,0.0,NaN,7.0,1
4,6910-9189,Blue,New,Camille,0,3,0.0,268.1717,Aki,Kindred,...,0,3,0.0,155.0397,Oh My God,1.0,0.0,NaN,3.0,0

# Quit nulls

In [22]:
for i in range(1,6):
    df[f"p{i}_pentakill"] = df[f"p{i}_pentakill"].fillna(0)
    #Debería rellenarse el dpm con una media del dpm que haya hecho el jugador?
    #ponerlo a 0 o eliminar dichas filas?
    #df[f"p{i}_dpm"] = df[f"p{i}_dpm"].fillna(0)
df["heralds"] = df["heralds"].fillna(0)

In [23]:
df.isnull().sum()

gameid            0
side              0
p1_name         107
p1_champion       0
p1_kills          0
p1_deaths         0
p1_pentakill      0
p1_dpm           12
p2_name         128
p2_champion       0
p2_kills          0
p2_deaths         0
p2_pentakill      0
p2_dpm           12
p3_name         113
p3_champion       0
p3_kills          0
p3_deaths         0
p3_pentakill      0
p3_dpm           12
p4_name          82
p4_champion       0
p4_kills          0
p4_deaths         0
p4_pentakill      0
p4_dpm           12
p5_name          78
p5_champion       0
p5_kills          0
p5_deaths         0
p5_pentakill      0
p5_dpm           12
team             21
dragons           0
barons            0
heralds           0
towers            0
result            0
dtype: int64

In [24]:
df["side"] = df["side"].map(lambda x: True if x =="Blue" else False)

In [25]:
df.head()

,gameid,side,p1_name,p1_champion,p1_kills,p1_deaths,p1_pentakill,p1_dpm,p2_name,p2_champion,...,p5_kills,p5_deaths,p5_pentakill,p5_dpm,team,dragons,barons,heralds,towers,result
0,6909-9183,True,369,Karma,0,0,0.0,539.8244,Karsa,Pantheon,...,0,4,0.0,71.4439,Top Esports,2.0,0.0,0.0,3.0,0
1,6909-9183,False,Bin,Aatrox,1,0,0.0,230.0780,SofM,Nidalee,...,0,2,0.0,113.1220,Suning,2.0,1.0,0.0,6.0,1
2,6909-9184,True,369,Jax,0,7,0.0,346.8273,Karsa,Hecarim,...,1,6,0.0,166.6399,Top Esports,3.0,2.0,0.0,6.0,0
3,6909-9184,False,Bin,Camille,11,3,0.0,688.4070,SofM,Lillia,...,0,4,0.0,316.5462,Suning,2.0,0.0,0.0,7.0,1
4,6910-9189,True,New,Camille,0,3,0.0,268.1717,Aki,Kindred,...,0,3,0.0,155.0397,Oh My God,1.0,0.0,0.0,3.0,0

In [27]:
df.to_csv(f"../Data/Procesed data/Re-formulated data/{year}_LoL_esports_match_data_from_OraclesElixir.csv")